#! /bin/bash
# based on https://gist.github.com/michalisFr/daa01c7374793a684a3a1f61e4959492
# https://github.com/paritytech/polkadot-sdk/releases/download/v1.1.0/polkadot

# !!!! Change variables below to your own !!!!
USER=polkadot
SERVICE_NAME=polkadot.service
BIN_DIR=/usr/bin
BASE_URL=https://github.com/paritytech/polkadot-sdk/releases/download/

wget ${BASE_URL}v$1/polkadot && \
wget ${BASE_URL}v$1/polkadot.sha256 && \
wget ${BASE_URL}v$1/polkadot-execute-worker && \
wget ${BASE_URL}v$1/polkadot-prepare-worker && \
sed -i 's+./artifacts/polkadot+polkadot+g' polkadot.sha256

if sha256sum -c polkadot.sha256 2>&1 | grep -q 'OK'
then
        echo "** SHA256 matches **"
        chmod +x polkadot && \
        chmod +x polkadot-execute-worker && \
        chmod +x polkadot-prepare-worker && \
        sudo chown ${USER}:${USER} polkadot && \
        sudo chown ${USER}:${USER} polkadot-execute-worker && \
        sudo chown ${USER}:${USER} polkadot-prepare-worker && \
        sudo systemctl stop ${SERVICE_NAME} && \
        mv polkadot ${BIN_DIR} && \
        mv polkadot-execute-worker ${BIN_DIR} && \
        mv polkadot-prepare-worker ${BIN_DIR} && \

        rm polkadot.sha256 && \
        sudo systemctl start ${SERVICE_NAME} && \
        sudo journalctl -fu ${SERVICE_NAME}
else
        echo "** SHA256 doesn't match. Aborting **"
        rm polkadot*
fi

echo done!
